In [362]:
import numpy as np
import math

In [363]:
n = 5
tamaño_poblacion = 30
numero_conexiones = int((n+1)*(n)/2)
posiciones = [np.array([0,0]) if i == 0 else np.random.randint(-30,30,2) for i in range(n+1)]
posiciones

[array([0, 0]),
 array([-30, -26]),
 array([-18,  25]),
 array([  5, -12]),
 array([  1, -30]),
 array([17,  5])]

In [364]:
distancias = []
for i in range(0,len(posiciones)):
    for j in range(i,len(posiciones)):
        if(j != i):
            distancias.append(math.dist(posiciones[i],posiciones[j]))
print(len(distancias))
print(distancias)

15
[39.698866482558415, 30.80584360149873, 13.0, 30.01666203960727, 17.720045146669353, 52.39274758971894, 37.696153649941536, 31.256999216175565, 56.302753041036986, 43.56604182158394, 58.189346103904626, 40.311288741492746, 18.439088914585778, 20.808652046684813, 38.48376280978771]


In [365]:
poblacion_inicial = np.random.randint(0,2,[tamaño_poblacion,numero_conexiones] )

In [366]:
fila = poblacion_inicial[0]
suma = sum(fila[:n])
penalizacion = False
if(suma == 0):
    penalizacion = True
'''for i in range(n-1):
    conta = 1
    suma = fila[indice_inicial:indice_final]
    indice_inicial = indice_final
    indice_final = indice_inicial+indice_inicial-1
    print(suma)'''

fila

array([0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0])

In [376]:
fila2 = poblacion_inicial[5]
n2 = n
fila = fila2.copy()
fila = fila.tolist()
conexiones = np.zeros(n)
conexiones_centro = np.zeros(n)
print(fila)
centros = fila[:n]

centros_flag = False
nodoFlag = False
if (np.sum(centros)== 0):
    centros_flag = True
else:
    for i in range(len(centros)):
        if centros[i] == 1:
            conexiones_centro[i] = 1

del fila [0:n2]

if not centros_flag:
    for i in range(n2-1):
        n2 -=1 
        nodo = fila[0:n2]
        for j in range(len(nodo)):
            if nodo[j]==1:
                conexiones[i] = 1
                conexiones[j+i] = 1
        del fila [0:n2]
else:
    nodoFlag = True

print(conexiones)
print(conexiones_centro)
print(f'bandera 1: {centros_flag}, bandera 2: {nodoFlag}')

[0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0]
[1. 1. 1. 1. 0.]
[0. 0. 1. 0. 1.]
bandera 1: False, bandera 2: False
