In [74]:
######### Importe librerias #########
import numpy as np
import math

In [75]:
######### Definicion valores #########
n = 5
tamaño_poblacion = 30
numero_conexiones = int((n+1)*(n)/2)
posiciones = [np.array([0,0]) if i == 0 else np.random.randint(-30,30,2) for i in range(n+1)]
distancias = []
for i in range(0,len(posiciones)):
    for j in range(i,len(posiciones)):
        if(j != i):
            distancias.append(math.dist(posiciones[i],posiciones[j]))

In [76]:
######### Poblacion inicial #########
poblacion_inicial = np.random.randint(0,2,[tamaño_poblacion,numero_conexiones] )

In [81]:
######### 
genotipo = poblacion_inicial[0]
print(genotipo)
penalizacion_central = False
central = genotipo[:n]
penalizacion_desconexion = False
n_indice = n
indice_inicial = 0
indice_final = n_indice
matriz_indices = np.zeros([n,n])
for i in range(n):
    contador = 0
    valor = genotipo[indice_inicial:indice_final]
    if i == 0:
        central = valor
        matriz_indices[n-1] = central
        if(sum(central) == 0):
            penalizacion_central = True
    else:
        for j in valor:
            if j == 1:
                matriz_indices[i-1][i-1] = 1
                matriz_indices[i-1][i+contador] = 1
            contador += 1
    n_indice -= 1
    indice_inicial = indice_final
    indice_final = indice_final + n_indice
busqueda_error = np.sum(matriz_indices[:-1], axis=0)
print(busqueda_error)
if 0 in busqueda_error:
    penalizacion_desconexion = True
print(matriz_indices)
print(penalizacion_central,penalizacion_desconexion)

    

[1 0 1 0 0 0 0 0 0 1 1 0 1 1 0]
[0. 1. 2. 2. 1.]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0.]]
False True


In [ ]:
fila2 = poblacion_inicial[5]
n2 = n
fila = fila2.copy()
fila = fila.tolist()
conexiones = np.zeros(n)
conexiones_centro = np.zeros(n)
print(fila)
centros = fila[:n]

centros_flag = False
nodoFlag = False
if (np.sum(centros)== 0):
    centros_flag = True
else:
    for i in range(len(centros)):
        if centros[i] == 1:
            conexiones_centro[i] = 1

del fila [0:n2]

if not centros_flag:
    for i in range(n2-1):
        n2 -=1 
        nodo = fila[0:n2]
        for j in range(len(nodo)):
            if nodo[j]==1:
                conexiones[i] = 1
                conexiones[j+i] = 1
        del fila [0:n2]
else:
    nodoFlag = True

print(conexiones)
print(conexiones_centro)
print(f'bandera 1: {centros_flag}, bandera 2: {nodoFlag}')