In [46]:
######### Importe librerias #########
import numpy as np
import math
import pandas as pd

In [3]:
######### Definicion valores #########
n = 5
tamaño_poblacion = 30
probabilidad_cruce = 0.2
numero_conexiones = int((n+1)*(n)/2)
posiciones = [np.array([0,0]) if i == 0 else np.random.randint(-30,30,2) for i in range(n+1)]
distancias = []
for i in range(0,len(posiciones)):
    for j in range(i,len(posiciones)):
        if(j != i):
            distancias.append(math.dist(posiciones[i],posiciones[j]))

In [4]:
######### Poblacion inicial #########
poblacion_inicial = np.random.randint(0,2,[tamaño_poblacion,numero_conexiones])

In [19]:
######### Funcion error #########
def funciones_penalizacion(genotipo):
    #genotipo = poblacion_inicial[0]
    #print(genotipo)
    penalizacion_central = False
    central = genotipo[:n]
    penalizacion_desconexion = False
    n_indice = n
    indice_inicial = 0
    indice_final = n_indice
    matriz_indices = np.zeros([n,n])
    for i in range(n):
        contador = 0
        valor = genotipo[indice_inicial:indice_final]
        if i == 0:
            central = valor
            matriz_indices[n-1] = central
            if(sum(central) == 0):
                penalizacion_central = True
        else:
            for j in valor:
                if j == 1:
                    matriz_indices[i-1][i-1] = 1
                    matriz_indices[i-1][i+contador] = 1
                contador += 1
        n_indice -= 1
        indice_inicial = indice_final
        indice_final = indice_final + n_indice
    busqueda_error = np.sum(matriz_indices, axis=0)
    #print(busqueda_error)
    if 0 in busqueda_error:
        penalizacion_desconexion = True
    #print(matriz_indices)
    #print(penalizacion_central,penalizacion_desconexion)
    return penalizacion_central or penalizacion_desconexion

    

In [22]:
vector_penalizacion = []        
for i in poblacion_inicial: ## verifica conexiones
    vector_penalizacion.append(funciones_penalizacion(i))
penalizacion = [2000 if i else 1 for i in vector_penalizacion] ## Penaliza con un valor de 2000 si no se hacen todas las conexiones

In [51]:
def metricas(poblacion,distancias):
    fitness = np.dot(poblacion_inicial,distancias)  ## Calcula funcion fitness
    fitness = fitness*penalizacion
    fitness_generacion = fitness.sum()
    fitness_average = fitness/fitness_generacion
    suma_fitness_average = fitness_average.sum()
    maximo_fitness = 1-fitness_average
    ponderado = maximo_fitness*tamaño_poblacion
    tabla_promedio = pd.DataFrame({'fitness':fitness,'f/sum':fitness_average,'Max':maximo_fitness,'fi/f * tpobl':ponderado_poblacion})
    tabla_promedio.head()
    return ponderado,fitness_generacion
### lo importante es ...


fitness     f/sum       Max  fi/f * tpobl
0     194.079051  0.000125  0.999875     29.996259
1  138429.630248  0.088951  0.911049     27.331477
2     191.725847  0.000123  0.999877     29.996304
3  296890.952667  0.190773  0.809227     24.276801
4     264.240364  0.000170  0.999830     29.994906

In [64]:
poblacion_intermedia = np.zeros([tamaño_poblacion,numero_conexiones])
for i in range(len(ponderado_poblacion)):
    indice_poblacion = np.argwhere(ponderado_poblacion==ponderado_poblacion.max())
    ponderado_poblacion[indice_poblacion] = ponderado_poblacion[indice_poblacion] - 1
    poblacion_intermedia[i]=(poblacion_inicial[indice_poblacion])
poblacion_intermedia

array([[0., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0.],
       [1., 1., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 1.],
       [1., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1.],
       [0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1.],
       [1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1.],
       [1., 0., 1., 0., 1., 1., 1., 1., 1., 0., 0., 1., 0., 1., 0.],
       [1., 0., 0., 1., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1.],
       [1., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1.],
       [1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1.],
       [0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1., 0.

In [12]:
busqueda_error = np.sum(matriz_indices, axis=0)
np.where(central==0)

(array([2, 4]),)

In [13]:
fila2 = poblacion_inicial[0]
n2 = n
fila = fila2.copy()
fila = fila.tolist()
conexiones = np.zeros(n)
conexiones_centro = np.zeros(n)
print(fila)
centros = fila[:n]

centros_flag = False
nodoFlag = False
if (np.sum(centros)== 0):
    centros_flag = True
else:
    for i in range(len(centros)):
        if centros[i] == 1:
            conexiones_centro[i] = 1

del fila [0:n2]

if not centros_flag:
    for i in range(n2-1):
        n2 -=1 
        nodo = fila[0:n2]
        for j in range(len(nodo)):
            if nodo[j]==1:
                conexiones[i] = 1
                conexiones[j+i] = 1
        del fila [0:n2]
else:
    nodoFlag = True

print(conexiones)
print(conexiones_centro)
print(f'bandera 1: {centros_flag}, bandera 2: {nodoFlag}')

[1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0]
[1. 1. 1. 1. 0.]
[1. 1. 0. 1. 0.]
bandera 1: False, bandera 2: False
